// Countries array
const countries: { id: number; country: string }[] = [
    { id: 1, country: "United States" },
    { id: 2, country: "United Kingdom" },
    { id: 3, country: "Canada" },
    { id: 4, country: "Australia" },
    { id: 5, country: "Germany" },
    { id: 6, country: "France" },
    { id: 7, country: "Spain" },
    { id: 8, country: "Italy" },
    { id: 9, country: "Japan" },
    { id: 10, country: "China" },
    { id: 11, country: "India" },
    { id: 12, country: "Brazil" },
    { id: 13, country: "Mexico" },
    { id: 14, country: "Russia" },
    { id: 15, country: "South Korea" },
    { id: 16, country: "Netherlands" },
    { id: 17, country: "Sweden" },
    { id: 18, country: "Norway" },
    { id: 19, country: "Denmark" },
    { id: 20, country: "Switzerland" },
    { id: 21, country: "Austria" },
    { id: 22, country: "Belgium" },
    { id: 23, country: "Portugal" },
    { id: 24, country: "Greece" },
    { id: 25, country: "Turkey" },
    { id: 26, country: "South Africa" },
    { id: 27, country: "Egypt" },
    { id: 28, country: "Nigeria" },
    { id: 29, country: "Kenya" },
    { id: 30, country: "Argentina" },
    { id: 31, country: "Chile" },
    { id: 32, country: "Colombia" },
    { id: 33, country: "Peru" },
    { id: 34, country: "Thailand" },
    { id: 35, country: "Vietnam" },
    { id: 36, country: "Indonesia" },
    { id: 37, country: "Malaysia" },
    { id: 38, country: "Singapore" },
    { id: 39, country: "Philippines" },
    { id: 40, country: "New Zealand" }
]

// Languages array
const languages: { id: number; language: string }[] = [
    { id: 1, language: "English" },
    { id: 2, language: "Spanish" },
    { id: 3, language: "French" },
    { id: 4, language: "German" },
    { id: 5, language: "Italian" },
    { id: 6, language: "Portuguese" },
    { id: 7, language: "Russian" },
    { id: 8, language: "Chinese (Mandarin)" },
    { id: 9, language: "Japanese" },
    { id: 10, language: "Korean" },
    { id: 11, language: "Arabic" },
    { id: 12, language: "Hindi" },
    { id: 13, language: "Bengali" },
    { id: 14, language: "Dutch" },
    { id: 15, language: "Swedish" },
    { id: 16, language: "Norwegian" },
    { id: 17, language: "Danish" },
    { id: 18, language: "Finnish" },
    { id: 19, language: "Polish" },
    { id: 20, language: "Czech" },
    { id: 21, language: "Hungarian" },
    { id: 22, language: "Romanian" },
    { id: 23, language: "Bulgarian" },
    { id: 24, language: "Greek" },
    { id: 25, language: "Turkish" },
    { id: 26, language: "Hebrew" },
    { id: 27, language: "Thai" },
    { id: 28, language: "Vietnamese" },
    { id: 29, language: "Indonesian" },
    { id: 30, language: "Malay" },
    { id: 31, language: "Tagalog" },
    { id: 32, language: "Swahili" },
    { id: 33, language: "Afrikaans" },
    { id: 34, language: "Urdu" },
    { id: 35, language: "Tamil" },
    { id: 36, language: "Telugu" },
    { id: 37, language: "Marathi" },
    { id: 38, language: "Gujarati" },
    { id: 39, language: "Punjabi" },
    { id: 40, language: "Ukrainian" }
]

export { countries, languages }
